
doctrine:
    dbal:
      db_driver: pdo_mysql    #
      db_host: 192.168.100.20  #
      db_port: 3306           #
      db_name: test           #
      db_user: root           #
      db_pwd: 123456       #
      db_dbms: mysql          #
      db_engine: MyISAM       #
      db_charset: utf8        #
services:
    database: Nette\Database\Connection( %dsn%, %user%, %password% )
    articleFactory: ArticleFactory

